---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: agf234/gradle
    tag: latest

run:
  path: pipeline-repo/ci/scripts/deploy.sh

inputs:
- name: pipeline-repo
- name: spring-music

